# Generated by Django 4.2.7 on 2023-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cardtext_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cardtext',
            field=models.CharField(default=5, max_length=100),
        ),
    ]
