# Generated by Django 4.2.7 on 2023-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_cardtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cardtext',
            field=models.CharField(default=5, max_length=100, unique=True),
        ),
    ]
